name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
       java-version: 1.8

#     - name: Grant execute permission for gradlew
#       run: chmod +x gradlew
#     - name: Build with Gradle
#       run: ./gradlew build
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Build APK
      run: bash ./gradlew assembleDebug --stacktrace
      
    - run: './gradlew assembleDebug'
    - uses: MeilCli/slack-upload-file@v1
      with:
        slack_token: 'xoxb-3331954140437-3359030754176-QzAJK78xncYXiSz8ZoMRSuKE'
        channels: 'apk-test'
        file_path: 'app/build/outputs/apk/debug/app-debug.apk'
        file_name: 'app-debug.apk'
        file_type: 'apk'
        initial_comment: '${{ github.ref }} 테스트 앱 슬랙 배포 성공'
        
    - name: 테스트용 apk artifact 업로드
      uses: actions/upload-artifact@v2
      with:
        name: app-debug-action.apk
        path: app/build/outputs/apk/debug/app-debug.apk
        
    - name: action-slack
      uses: 8398a7/action-slack@v3.8.0
      with:
        status: ${{ job.status }}
        author_name: 빌드 알림
      env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
